// Copyright (c) 2026 Devlas SpA — https://devlas.cl
// Licencia MIT. Ver archivo LICENSE para mas detalles.
/**
 * comunaOficina.js
 *
 * Mapa de comuna → oficina SII para el campo siiOficina de muestras impresas.
 * Generado consultando https://www.sii.cl/ayudas/asistencia/oficinas/
 *
 * Formato: 'S.I.I. - NOMBRE_CORTO'  (igual al default histórico 'S.I.I. - SANTIAGO CENTRO')
 */

'use strict';

/** @type {Record<string, string>} */
const COMUNA_OFICINA_SII = {
  // ── REGIÓN 1: Arica y Parinacota ─────────────────────────────────────────
  'arica':                   'S.I.I. - ARICA',
  'camarones':               'S.I.I. - ARICA',
  'putre':                   'S.I.I. - ARICA',
  'general lagos':           'S.I.I. - ARICA',

  // ── REGIÓN 2: Tarapacá ───────────────────────────────────────────────────
  'iquique':                 'S.I.I. - IQUIQUE',
  'alto hospicio':           'S.I.I. - IQUIQUE',
  'pica':                    'S.I.I. - IQUIQUE',
  'pozo almonte':            'S.I.I. - IQUIQUE',
  'huara':                   'S.I.I. - IQUIQUE',
  'camiña':                  'S.I.I. - IQUIQUE',
  'camina':                  'S.I.I. - IQUIQUE',
  'colchane':                'S.I.I. - IQUIQUE',

  // ── REGIÓN 3: Antofagasta ────────────────────────────────────────────────
  'antofagasta':             'S.I.I. - ANTOFAGASTA',
  'mejillones':              'S.I.I. - ANTOFAGASTA',
  'sierra gorda':            'S.I.I. - ANTOFAGASTA',
  'taltal':                  'S.I.I. - ANTOFAGASTA',
  'tocopilla':               'S.I.I. - ANTOFAGASTA',
  'maria elena':             'S.I.I. - ANTOFAGASTA',
  // Unidad Calama
  'calama':                  'S.I.I. - CALAMA',
  'san pedro de atacama':    'S.I.I. - CALAMA',
  'ollague':                 'S.I.I. - CALAMA',
  'ollagüe':                 'S.I.I. - CALAMA',

  // ── REGIÓN 4: Atacama ────────────────────────────────────────────────────
  'copiapó':                 'S.I.I. - COPIAPÓ',
  'copiapo':                 'S.I.I. - COPIAPÓ',
  'caldera':                 'S.I.I. - COPIAPÓ',
  'tierra amarilla':         'S.I.I. - COPIAPÓ',
  'chañaral':                'S.I.I. - COPIAPÓ',
  'chanaral':                'S.I.I. - COPIAPÓ',
  'diego de almagro':        'S.I.I. - COPIAPÓ',
  // Unidad Vallenar
  'vallenar':                'S.I.I. - VALLENAR',
  'freirina':                'S.I.I. - VALLENAR',
  'huasco':                  'S.I.I. - VALLENAR',
  'alto del carmen':         'S.I.I. - VALLENAR',

  // ── REGIÓN 5: Coquimbo ───────────────────────────────────────────────────
  'la serena':               'S.I.I. - LA SERENA',
  'la higuera':              'S.I.I. - LA SERENA',
  'paihuano':                'S.I.I. - LA SERENA',
  'andacollo':               'S.I.I. - LA SERENA',
  'vicuña':                  'S.I.I. - LA SERENA',
  'vicuna':                  'S.I.I. - LA SERENA',
  // Unidad Coquimbo
  'coquimbo':                'S.I.I. - COQUIMBO',
  // (Ovalle, Illapel, etc. comparten D. Regional La Serena o tienen unidades propias)
  'ovalle':                  'S.I.I. - LA SERENA',
  'illapel':                 'S.I.I. - LA SERENA',
  'salamanca':               'S.I.I. - LA SERENA',

  // ── REGIÓN 6: Valparaíso ─────────────────────────────────────────────────
  'valparaíso':              'S.I.I. - VALPARAÍSO',
  'valparaiso':              'S.I.I. - VALPARAÍSO',
  'casablanca':              'S.I.I. - VALPARAÍSO',
  'juan fernández':          'S.I.I. - VALPARAÍSO',
  'juan fernandez':          'S.I.I. - VALPARAÍSO',
  'isla de pascua':          'S.I.I. - VALPARAÍSO',
  // Unidad Viña del Mar
  'viña del mar':            'S.I.I. - VIÑA DEL MAR',
  'vina del mar':            'S.I.I. - VIÑA DEL MAR',
  'concón':                  'S.I.I. - VIÑA DEL MAR',
  'concon':                  'S.I.I. - VIÑA DEL MAR',
  'quintero':                'S.I.I. - VIÑA DEL MAR',
  'puchuncaví':              'S.I.I. - VIÑA DEL MAR',
  'puchuncavi':              'S.I.I. - VIÑA DEL MAR',
  // Unidad San Antonio
  'san antonio':             'S.I.I. - SAN ANTONIO',
  'santo domingo':           'S.I.I. - SAN ANTONIO',
  'navidad':                 'S.I.I. - SAN ANTONIO',
  'cartagena':               'S.I.I. - SAN ANTONIO',
  'el tabo':                 'S.I.I. - SAN ANTONIO',
  'el quisco':               'S.I.I. - SAN ANTONIO',
  'algarrobo':               'S.I.I. - SAN ANTONIO',
  // Unidad Los Andes
  'los andes':               'S.I.I. - LOS ANDES',
  'calle larga':             'S.I.I. - LOS ANDES',
  'san esteban':             'S.I.I. - LOS ANDES',
  'rinconada':               'S.I.I. - LOS ANDES',
  // Unidad San Felipe
  'san felipe':              'S.I.I. - SAN FELIPE',
  'panquehue':               'S.I.I. - SAN FELIPE',
  'catemu':                  'S.I.I. - SAN FELIPE',
  'putaendo':                'S.I.I. - SAN FELIPE',
  'llay llay':               'S.I.I. - SAN FELIPE',
  // Unidad Villa Alemana (Quilpué + Villa Alemana)
  'villa alemana':           'S.I.I. - VILLA ALEMANA',
  'quilpué':                 'S.I.I. - VILLA ALEMANA',
  'quilpue':                 'S.I.I. - VILLA ALEMANA',
  // Unidad Quillota
  'quillota':                'S.I.I. - VALPARAÍSO',
  'la calera':               'S.I.I. - VALPARAÍSO',
  'la cruz':                 'S.I.I. - VALPARAÍSO',
  'nogales':                 'S.I.I. - VALPARAÍSO',
  'hijuelas':                'S.I.I. - VALPARAÍSO',
  'olmué':                   'S.I.I. - VALPARAÍSO',
  'olmue':                   'S.I.I. - VALPARAÍSO',
  'limache':                 'S.I.I. - VALPARAÍSO',
  'la ligua':                'S.I.I. - VALPARAÍSO',
  'petorca':                 'S.I.I. - VALPARAÍSO',
  'cabildo':                 'S.I.I. - VALPARAÍSO',
  'papudo':                  'S.I.I. - VALPARAÍSO',
  'zapallar':                'S.I.I. - VALPARAÍSO',

  // ── REGIÓN 7: Metropolitana ──────────────────────────────────────────────
  // D.R. Santiago Centro
  'santiago':                'S.I.I. - SANTIAGO CENTRO',
  // D.R. Santiago Oriente
  'las condes':              'S.I.I. - SANTIAGO ORIENTE',
  'lo barnechea':            'S.I.I. - SANTIAGO ORIENTE',
  'vitacura':                'S.I.I. - SANTIAGO ORIENTE',
  // D.R. Santiago Norte
  'independencia':           'S.I.I. - SANTIAGO NORTE',
  'recoleta':                'S.I.I. - SANTIAGO NORTE',
  'huechuraba':              'S.I.I. - SANTIAGO NORTE',
  'conchalí':                'S.I.I. - SANTIAGO NORTE',
  'conchali':                'S.I.I. - SANTIAGO NORTE',
  'quilicura':               'S.I.I. - SANTIAGO NORTE',
  'colina':                  'S.I.I. - SANTIAGO NORTE',
  'lampa':                   'S.I.I. - SANTIAGO NORTE',
  'til-til':                 'S.I.I. - SANTIAGO NORTE',
  'tiltil':                  'S.I.I. - SANTIAGO NORTE',
  // D.R. Santiago Poniente
  'cerro navia':             'S.I.I. - SANTIAGO PONIENTE',
  'curacaví':                'S.I.I. - SANTIAGO PONIENTE',
  'curacavi':                'S.I.I. - SANTIAGO PONIENTE',
  'estación central':        'S.I.I. - SANTIAGO PONIENTE',
  'estacion central':        'S.I.I. - SANTIAGO PONIENTE',
  'lo prado':                'S.I.I. - SANTIAGO PONIENTE',
  'pudahuel':                'S.I.I. - SANTIAGO PONIENTE',
  'quinta normal':           'S.I.I. - SANTIAGO PONIENTE',
  'renca':                   'S.I.I. - SANTIAGO PONIENTE',
  // D.R. Santiago Sur
  'san miguel':              'S.I.I. - SANTIAGO SUR',
  'la cisterna':             'S.I.I. - SANTIAGO SUR',
  'san joaquín':             'S.I.I. - SANTIAGO SUR',
  'san joaquin':             'S.I.I. - SANTIAGO SUR',
  'pedro aguirre cerda':     'S.I.I. - SANTIAGO SUR',
  'lo espejo':               'S.I.I. - SANTIAGO SUR',
  'la granja':               'S.I.I. - SANTIAGO SUR',
  'la pintana':              'S.I.I. - SANTIAGO SUR',
  'san ramón':               'S.I.I. - SANTIAGO SUR',
  'san ramon':               'S.I.I. - SANTIAGO SUR',
  // Unidad Ñuñoa
  'ñuñoa':                   'S.I.I. - ÑUÑOA',
  'nunoa':                   'S.I.I. - ÑUÑOA',
  'la reina':                'S.I.I. - ÑUÑOA',
  'macul':                   'S.I.I. - ÑUÑOA',
  'peñalolén':               'S.I.I. - ÑUÑOA',
  'penalolen':               'S.I.I. - ÑUÑOA',
  // Unidad Maipú
  'maipú':                   'S.I.I. - MAIPÚ',
  'maipu':                   'S.I.I. - MAIPÚ',
  'cerrillos':               'S.I.I. - MAIPÚ',
  'el monte':                'S.I.I. - MAIPÚ',
  'isla de maipo':           'S.I.I. - MAIPÚ',
  'padre hurtado':           'S.I.I. - MAIPÚ',
  'peñaflor':                'S.I.I. - MAIPÚ',
  'penaflor':                'S.I.I. - MAIPÚ',
  'talagante':               'S.I.I. - MAIPÚ',
  // Unidad La Florida
  'la florida':              'S.I.I. - LA FLORIDA',
  'puente alto':             'S.I.I. - LA FLORIDA',
  'pirque':                  'S.I.I. - LA FLORIDA',
  'san josé de maipo':       'S.I.I. - LA FLORIDA',
  'san jose de maipo':       'S.I.I. - LA FLORIDA',
  // Unidad Providencia
  'providencia':             'S.I.I. - PROVIDENCIA',
  // Unidad San Bernardo
  'san bernardo':            'S.I.I. - SAN BERNARDO',
  'calera de tango':         'S.I.I. - SAN BERNARDO',
  'el bosque':               'S.I.I. - SAN BERNARDO',
  // Unidad Buin
  'buin':                    'S.I.I. - BUIN',
  'paine':                   'S.I.I. - BUIN',
  // Melipilla (comparte D.R. Santiago Poniente en algunos esquemas)
  'melipilla':               'S.I.I. - SANTIAGO PONIENTE',
  'alhué':                   'S.I.I. - SANTIAGO PONIENTE',
  'alhue':                   'S.I.I. - SANTIAGO PONIENTE',
  'san pedro':               'S.I.I. - SANTIAGO PONIENTE',

  // ── REGIÓN 8: O'Higgins ──────────────────────────────────────────────────
  'rancagua':                'S.I.I. - RANCAGUA',
  'machalí':                 'S.I.I. - RANCAGUA',
  'machali':                 'S.I.I. - RANCAGUA',
  'graneros':                'S.I.I. - RANCAGUA',
  'san francisco de mostazal': 'S.I.I. - RANCAGUA',
  'doñihue':                 'S.I.I. - RANCAGUA',
  'donihue':                 'S.I.I. - RANCAGUA',
  'codegua':                 'S.I.I. - RANCAGUA',
  'rengo':                   'S.I.I. - RANCAGUA',
  'coltauco':                'S.I.I. - RANCAGUA',
  'requinoa':                'S.I.I. - RANCAGUA',
  'olivar':                  'S.I.I. - RANCAGUA',
  'malloa':                  'S.I.I. - RANCAGUA',
  'quinta de tilcoco':       'S.I.I. - RANCAGUA',
  'coinco':                  'S.I.I. - RANCAGUA',
  // Resto de O'Higgins → Rancagua como capital de región
  'san fernando':            'S.I.I. - RANCAGUA',
  'santa cruz':              'S.I.I. - RANCAGUA',
  'pichilemu':               'S.I.I. - RANCAGUA',

  // ── REGIÓN 9: Maule ──────────────────────────────────────────────────────
  'talca':                   'S.I.I. - TALCA',
  'san clemente':            'S.I.I. - TALCA',
  'pelarco':                 'S.I.I. - TALCA',
  'río claro':               'S.I.I. - TALCA',
  'rio claro':               'S.I.I. - TALCA',
  'pencahue':                'S.I.I. - TALCA',
  'maule':                   'S.I.I. - TALCA',
  'curepto':                 'S.I.I. - TALCA',
  'san javier':              'S.I.I. - TALCA',
  'san rafael':              'S.I.I. - TALCA',
  'constitución':            'S.I.I. - TALCA',
  'constitucion':            'S.I.I. - TALCA',
  'empedrado':               'S.I.I. - TALCA',
  // Unidad Curicó
  'curicó':                  'S.I.I. - CURICÓ',
  'curico':                  'S.I.I. - CURICÓ',
  'teno':                    'S.I.I. - CURICÓ',
  'romeral':                 'S.I.I. - CURICÓ',
  'molina':                  'S.I.I. - CURICÓ',
  'hualañe':                 'S.I.I. - CURICÓ',
  'hualane':                 'S.I.I. - CURICÓ',
  'sagrada familia':         'S.I.I. - CURICÓ',
  'licantén':                'S.I.I. - CURICÓ',
  'licanten':                'S.I.I. - CURICÓ',
  'vichuquén':               'S.I.I. - CURICÓ',
  'vichuquen':               'S.I.I. - CURICÓ',
  'rauco':                   'S.I.I. - CURICÓ',
  // Linares → Talca
  'linares':                 'S.I.I. - TALCA',
  'longaví':                 'S.I.I. - TALCA',
  'longavi':                 'S.I.I. - TALCA',
  'parral':                  'S.I.I. - TALCA',
  'cauquenes':               'S.I.I. - TALCA',

  // ── REGIÓN 10: Bío Bío ───────────────────────────────────────────────────
  'concepción':              'S.I.I. - CONCEPCIÓN',
  'concepcion':              'S.I.I. - CONCEPCIÓN',
  'chiguayante':             'S.I.I. - CONCEPCIÓN',
  'san pedro de la paz':     'S.I.I. - CONCEPCIÓN',
  'penco':                   'S.I.I. - CONCEPCIÓN',
  'hualqui':                 'S.I.I. - CONCEPCIÓN',
  'florida':                 'S.I.I. - CONCEPCIÓN',
  'tomé':                    'S.I.I. - CONCEPCIÓN',
  'tome':                    'S.I.I. - CONCEPCIÓN',
  'coronel':                 'S.I.I. - CONCEPCIÓN',
  'lota':                    'S.I.I. - CONCEPCIÓN',
  'santa juana':             'S.I.I. - CONCEPCIÓN',
  'arauco':                  'S.I.I. - CONCEPCIÓN',
  'lebu':                    'S.I.I. - CONCEPCIÓN',
  'cañete':                  'S.I.I. - CONCEPCIÓN',
  'canete':                  'S.I.I. - CONCEPCIÓN',
  'tirúa':                   'S.I.I. - CONCEPCIÓN',
  'tirua':                   'S.I.I. - CONCEPCIÓN',
  'curanilahue':             'S.I.I. - CONCEPCIÓN',
  'los álamos':              'S.I.I. - CONCEPCIÓN',
  'los alamos':              'S.I.I. - CONCEPCIÓN',
  // Unidad Los Ángeles
  'los ángeles':             'S.I.I. - LOS ÁNGELES',
  'los angeles':             'S.I.I. - LOS ÁNGELES',
  'santa bárbara':           'S.I.I. - LOS ÁNGELES',
  'santa barbara':           'S.I.I. - LOS ÁNGELES',
  'laja':                    'S.I.I. - LOS ÁNGELES',
  'quilleco':                'S.I.I. - LOS ÁNGELES',
  'nacimiento':              'S.I.I. - LOS ÁNGELES',
  'negrete':                 'S.I.I. - LOS ÁNGELES',
  'mulchén':                 'S.I.I. - LOS ÁNGELES',
  'mulchen':                 'S.I.I. - LOS ÁNGELES',
  'quilaco':                 'S.I.I. - LOS ÁNGELES',
  'yumbel':                  'S.I.I. - LOS ÁNGELES',
  'cabrero':                 'S.I.I. - LOS ÁNGELES',
  'san rosendo':             'S.I.I. - LOS ÁNGELES',
  'tucapel':                 'S.I.I. - LOS ÁNGELES',
  'antuco':                  'S.I.I. - LOS ÁNGELES',
  'alto bío-bío':            'S.I.I. - LOS ÁNGELES',
  'alto biobio':             'S.I.I. - LOS ÁNGELES',

  // ── REGIÓN 11: Araucanía ─────────────────────────────────────────────────
  'temuco':                  'S.I.I. - TEMUCO',
  'vilcún':                  'S.I.I. - TEMUCO',
  'vilcun':                  'S.I.I. - TEMUCO',
  'freire':                  'S.I.I. - TEMUCO',
  'cunco':                   'S.I.I. - TEMUCO',
  'lautaro':                 'S.I.I. - TEMUCO',
  'perquenco':               'S.I.I. - TEMUCO',
  'galvarino':               'S.I.I. - TEMUCO',
  'nueva imperial':          'S.I.I. - TEMUCO',
  'carahue':                 'S.I.I. - TEMUCO',
  'puerto saavedra':         'S.I.I. - TEMUCO',
  'pitrufquén':              'S.I.I. - TEMUCO',
  'pitrufquen':              'S.I.I. - TEMUCO',
  'gorbea':                  'S.I.I. - TEMUCO',
  'toltén':                  'S.I.I. - TEMUCO',
  'tolten':                  'S.I.I. - TEMUCO',
  'loncoche':                'S.I.I. - TEMUCO',
  'melipeuco':               'S.I.I. - TEMUCO',
  'teodoro schmidt':         'S.I.I. - TEMUCO',
  'padre las casas':         'S.I.I. - TEMUCO',
  'cholchol':                'S.I.I. - TEMUCO',
  'angol':                   'S.I.I. - TEMUCO',
  'victoria':                'S.I.I. - TEMUCO',
  'traiguén':                'S.I.I. - TEMUCO',
  'traiguen':                'S.I.I. - TEMUCO',
  'los sauces':              'S.I.I. - TEMUCO',
  'lumaco':                  'S.I.I. - TEMUCO',
  'purén':                   'S.I.I. - TEMUCO',
  'puren':                   'S.I.I. - TEMUCO',
  'collipulli':              'S.I.I. - TEMUCO',
  'ercilla':                 'S.I.I. - TEMUCO',
  'curacautín':              'S.I.I. - TEMUCO',
  'curacautin':              'S.I.I. - TEMUCO',
  'lonquimay':               'S.I.I. - TEMUCO',
  'villarrica':              'S.I.I. - TEMUCO',
  'pucón':                   'S.I.I. - TEMUCO',
  'pucon':                   'S.I.I. - TEMUCO',
  'curarrehue':              'S.I.I. - TEMUCO',

  // ── REGIÓN 12: Los Ríos ──────────────────────────────────────────────────
  'valdivia':                'S.I.I. - VALDIVIA',
  'máfil':                   'S.I.I. - VALDIVIA',
  'mafil':                   'S.I.I. - VALDIVIA',
  'corral':                  'S.I.I. - VALDIVIA',
  'los lagos':               'S.I.I. - VALDIVIA',
  'paillaco':                'S.I.I. - VALDIVIA',
  'futrono':                 'S.I.I. - VALDIVIA',
  'río bueno':               'S.I.I. - VALDIVIA',
  'rio bueno':               'S.I.I. - VALDIVIA',
  'la unión':                'S.I.I. - VALDIVIA',
  'la union':                'S.I.I. - VALDIVIA',
  'lago ranco':              'S.I.I. - VALDIVIA',
  'mariquina':               'S.I.I. - VALDIVIA',
  'lanco':                   'S.I.I. - VALDIVIA',

  // ── REGIÓN 13: Los Lagos ─────────────────────────────────────────────────
  'puerto montt':            'S.I.I. - PUERTO MONTT',
  'calbuco':                 'S.I.I. - PUERTO MONTT',
  'maullín':                 'S.I.I. - PUERTO MONTT',
  'maullin':                 'S.I.I. - PUERTO MONTT',
  'los muermos':             'S.I.I. - PUERTO MONTT',
  'hualaihué':               'S.I.I. - PUERTO MONTT',
  'hualaihue':               'S.I.I. - PUERTO MONTT',
  'cochamó':                 'S.I.I. - PUERTO MONTT',
  'cochamo':                 'S.I.I. - PUERTO MONTT',
  'puerto varas':            'S.I.I. - PUERTO MONTT',
  'llanquihue':              'S.I.I. - PUERTO MONTT',
  'fresia':                  'S.I.I. - PUERTO MONTT',
  'frutillar':               'S.I.I. - PUERTO MONTT',
  'los llanos':              'S.I.I. - PUERTO MONTT',
  // Unidad Osorno
  'osorno':                  'S.I.I. - OSORNO',
  'puyehue':                 'S.I.I. - OSORNO',
  'purranque':               'S.I.I. - OSORNO',
  'río negro':               'S.I.I. - OSORNO',
  'rio negro':               'S.I.I. - OSORNO',
  'san pablo':               'S.I.I. - OSORNO',
  'san juan de la costa':    'S.I.I. - OSORNO',
  'puerto octay':            'S.I.I. - OSORNO',
  // Ancud/Castro → Puerto Montt
  'ancud':                   'S.I.I. - PUERTO MONTT',
  'castro':                  'S.I.I. - PUERTO MONTT',
  'chonchi':                 'S.I.I. - PUERTO MONTT',
  'quellón':                 'S.I.I. - PUERTO MONTT',
  'quellon':                 'S.I.I. - PUERTO MONTT',
  'dalcahue':                'S.I.I. - PUERTO MONTT',

  // ── REGIÓN 14: Aysén ─────────────────────────────────────────────────────
  'coyhaique':               'S.I.I. - COYHAIQUE',
  'río ibáñez':              'S.I.I. - COYHAIQUE',
  'rio ibanez':              'S.I.I. - COYHAIQUE',
  'tortel':                  'S.I.I. - COYHAIQUE',
  'cochrane':                'S.I.I. - COYHAIQUE',
  'chile chico':             'S.I.I. - COYHAIQUE',
  'aysén':                   'S.I.I. - COYHAIQUE',
  'aysen':                   'S.I.I. - COYHAIQUE',
  'cisnes':                  'S.I.I. - COYHAIQUE',
  'lago verde':              'S.I.I. - COYHAIQUE',
  'guaitecas':               'S.I.I. - COYHAIQUE',

  // ── REGIÓN 15: Magallanes ────────────────────────────────────────────────
  'punta arenas':            'S.I.I. - PUNTA ARENAS',
  'río verde':               'S.I.I. - PUNTA ARENAS',
  'rio verde':               'S.I.I. - PUNTA ARENAS',
  'san gregorio':            'S.I.I. - PUNTA ARENAS',
  'laguna blanca':           'S.I.I. - PUNTA ARENAS',
  'cabo de hornos':          'S.I.I. - PUNTA ARENAS',
  'puerto natales':          'S.I.I. - PUNTA ARENAS',
  'natales':                 'S.I.I. - PUNTA ARENAS',
  'torres del paine':        'S.I.I. - PUNTA ARENAS',
  'porvenir':                'S.I.I. - PUNTA ARENAS',
  'primavera':               'S.I.I. - PUNTA ARENAS',
  'timaukel':                'S.I.I. - PUNTA ARENAS',
  'puerto williams':         'S.I.I. - PUNTA ARENAS',

  // ── REGIÓN 16: Ñuble ─────────────────────────────────────────────────────
  'chillán':                 'S.I.I. - CHILLÁN',
  'chillan':                 'S.I.I. - CHILLÁN',
  'chillán viejo':           'S.I.I. - CHILLÁN',
  'chillan viejo':           'S.I.I. - CHILLÁN',
  'coihueco':                'S.I.I. - CHILLÁN',
  'pinto':                   'S.I.I. - CHILLÁN',
  'el carmen':               'S.I.I. - CHILLÁN',
  'san ignacio':             'S.I.I. - CHILLÁN',
  'pemuco':                  'S.I.I. - CHILLÁN',
  'yungay':                  'S.I.I. - CHILLÁN',
  'bulnes':                  'S.I.I. - CHILLÁN',
  'quillón':                 'S.I.I. - CHILLÁN',
  'quillon':                 'S.I.I. - CHILLÁN',
  'ranquil':                 'S.I.I. - CHILLÁN',
  'portezuelo':              'S.I.I. - CHILLÁN',
  'coelemu':                 'S.I.I. - CHILLÁN',
  'trehuaco':                'S.I.I. - CHILLÁN',
  'quirihue':                'S.I.I. - CHILLÁN',
  'cobquecura':              'S.I.I. - CHILLÁN',
  'ninhue':                  'S.I.I. - CHILLÁN',
  'san carlos':              'S.I.I. - CHILLÁN',
  'ñiquén':                  'S.I.I. - CHILLÁN',
  'niquen':                  'S.I.I. - CHILLÁN',
  'san fabián':              'S.I.I. - CHILLÁN',
  'san fabian':              'S.I.I. - CHILLÁN',
  'san nicolás':             'S.I.I. - CHILLÁN',
  'san nicolas':             'S.I.I. - CHILLÁN',
};

/**
 * Devuelve el nombre de la oficina SII para imprimir en la muestra impresa.
 * Formato: 'S.I.I. - NOMBRE_OFICINA'
 *
 * @param {string} comuna - Nombre de la comuna (se normaliza automáticamente)
 * @returns {string} Nombre de oficina, o null si no se encuentra
 */
function getOficinaForComuna(comuna) {
  if (!comuna || typeof comuna !== 'string') return null;
  const key = comuna.trim().toLowerCase();
  return COMUNA_OFICINA_SII[key] || null;
}

module.exports = { COMUNA_OFICINA_SII, getOficinaForComuna };
